CREATE TABLE patient_variables (
  caseid integer NOT NULL,
  year integer,
  sex text,
  age integer,
  smoker boolean,
  alcohol boolean,
  dnr boolean,
  ventilat boolean,
  hxcopd boolean,
  cpneumon boolean,
  hxchf boolean,
  cardiac_surgery boolean,
  renalfail boolean,
  dialysis boolean,
  discancr boolean,
  preop_wndinf boolean,
  steroid_immunosup boolean,
  wtloss boolean,
  bleeddis boolean,
  preop_transfus boolean,
  pregnancy boolean,
  priorop boolean,
  race text,
  bmi real,
  asa integer,
  diabetes text,
  dyspnea text,
  fnstatus text,
  liver boolean,
  heart boolean,
  pvd boolean,
  neuro boolean,
  plegia boolean,
  chemo_radio boolean,
  infx text,
  lab_sodium real,
  lab_bun real,
  lab_creatine real,
  lab_albumin real,
  lab_bili real,
  lab_ast real,
  lab_alkphos real,
  lab_wbc real,
  lab_hct real,
  lab_plt real,
  lab_ptt real,
  lab_inr real,
  podiag text,
  workrvu real,
  pgy integer,
  emergency boolean,
  optime integer,
  general_anes boolean,
  other_proc boolean,
  concurrent_proc boolean,
  wound text,
  cpt_type text,
  ccs_category text,
  cpt text,
  cpt_mis boolean,
  cpt_implant boolean,
  CONSTRAINT calypso_pkey PRIMARY KEY (caseid),
  CONSTRAINT calypso_diabetes_check CHECK (diabetes = ANY (ARRAY['non-insulin'::text, 'insulin'::text, 'no'::text])),
  CONSTRAINT calypso_dyspnea_check CHECK (dyspnea = ANY (ARRAY['at rest'::text, 'moderate exertion'::text, 'no'::text])),
  CONSTRAINT calypso_fnstatus_check CHECK (fnstatus = ANY (ARRAY['independent'::text, 'partially dependent'::text, 'totally dependent'::text])),
  CONSTRAINT calypso_infx_check CHECK (infx = ANY (ARRAY['SIRS'::text, 'sepsis'::text, 'septic shock'::text, 'no'::text])),
  CONSTRAINT calypso_podiag_check CHECK (podiag = ANY (ARRAY['neoplasm'::text, 'infection'::text, 'no'::text])),
  CONSTRAINT calypso_race_check CHECK (race = ANY (ARRAY['asian'::text, 'black'::text, 'other'::text])),
  CONSTRAINT calypso_sex_check CHECK (sex = ANY (ARRAY['female'::text, 'male'::text])),
  CONSTRAINT calypso_wound_check CHECK (wound = ANY (ARRAY['contaminated'::text, 'dirty'::text, 'clean contaminated'::text, 'clean'::text]))
);